name: Build Artifact

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 安装依赖并构建
        run: |
          pnpm install
          pnpm run build
          mkdir -p ${{ runner.temp }}/temp/plugin
          cp -r README.md LICENSE ${{ runner.temp }}/temp/plugin

      - name: 删除开发依赖并移动构建产物
        run: |
          npm pkg delete devDependencies
          cp -r package.json lib CHANGELOG.md ${{ runner.temp }}/temp/plugin
        working-directory: packages/core
      - name: 上传编译产物到artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: core-build
          path: ${{ runner.temp }}/temp/plugin